apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      #targetPort: <Mesmo valor de port>
  selector:
    app: primeiro-pod
